travis:
  secure:
    BINSTAR_TOKEN: HmyS0cI4WxU9s9eQ4+TSM8EKRrmxE8La+i4Bhh69wKTHmfrTwEziCpS5UqNHELrc8zOo69wqAzaUhBQ9RuZJqRN9ePAhDjCEQ2Hs+1hGjUG6mRsDhfobSlajEo2Mto37uE8STMaTOX3djitcmoBglHnwWxA493QzjWI0r2obzerptIzKwhkFm3kGI2s9OAGaB3WuynFIljODUqXBmJBcZcx2OA9nF5hQMbDvgmHqRYF34NzMAErjx6qHUQNaA7FaIFTPUSzPeU9Owm/7NAM7q3hJYMEBPlwhvkGlf7ohEg35FHJoSB7vfmqCt+/NRgudOgGF0Q5wWzyMtWThD/Y5nqVGvDmr8KYQZFzlaFenWWmeIHeBYLHD2XDmqaljAnz/gzOChdahyIhtqpjcIUHYOvFTsMRDyehocsR8+hce0ZEzB2p4pC8D6IlPbQ8HrlVE4fLTLC2NBNOqjSy1l9MF3GSA1CaM+GH3oV4jj93QltglUIR0l8DMVPg60idJQZc0EajbOvW6vt0Y0BsdupDoGXDICuANEC3fIbJI9HKpCkZyU+29SOj6+je/esTLcteUI5eja+Ka+kfi1LHwDJzPGgbwIIghAP/ahaHddHcttV+gCe2CsrQQ/rciPlngK0Uyjpazo4XHBR9AYTilaa6Tpgt3cWY8HkdT3GcHjQq+gvU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
